(lang dune 3.6)

(name tiger)

(source
 (github cdmistman/modern_compiler))

(package
 (name chap01)
 (depends ocaml dune))

(package
  (name lexical_analysis)
  (depends ocaml dune))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
